# Generated by Django 3.2.13 on 2022-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battery",
            name="serial_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="gpstracker",
            name="serial_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="address",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="area",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vehiclestatuslogs",
            name="new_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehiclestatuslogs",
            name="old_status",
            field=models.CharField(max_length=50),
        ),
    ]
