# Generated by Django 4.1 on 2022-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0004_auto_20220705_1222"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="battery",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="gpstracker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
