# Generated by Django 4.1 on 2022-09-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_alter_vendor_type"),
        ("fleets", "0005_alter_station_options_alter_vehicle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vendors.vendor",
            ),
        ),
    ]
