# Generated by Django 4.1 on 2022-09-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0006_vehicle_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="city",
        ),
    ]
