# Generated by Django 3.2.13 on 2022-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0007_remove_vehicle_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'For Deployment'), (1, 'On Ground'), (2, 'Under Maintenance'), (3, 'Under Servicing'), (4, 'Backup')]),
        ),
        migrations.AlterField(
            model_name='vehiclestatuslogs',
            name='new_status',
            field=models.IntegerField(choices=[(0, 'For Deployment'), (1, 'On Ground'), (2, 'Under Maintenance'), (3, 'Under Servicing'), (4, 'Backup')]),
        ),
        migrations.AlterField(
            model_name='vehiclestatuslogs',
            name='old_status',
            field=models.IntegerField(choices=[(0, 'For Deployment'), (1, 'On Ground'), (2, 'Under Maintenance'), (3, 'Under Servicing'), (4, 'Backup')]),
        ),
    ]
