# Generated by Django 3.2.13 on 2022-12-15 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid

def set_station_code(apps, schema_editor):
    Station = apps.get_model('fleets', 'Station')
    for row in Station.objects.all():
        row.code = str(row.city)[:3].upper() + str(uuid.uuid4().time_low)[-4:]
        row.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_type'),
        ('fleets', '0009_auto_20221215_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle'),
        ),
        migrations.AlterField(
            model_name='gpstracker',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer', to='vendors.vendor'),
        ),
        migrations.RunPython(set_station_code, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
