# Generated by Django 3.2.13 on 2022-12-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0010_auto_20221215_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
