# Generated by Django 3.2.13 on 2022-12-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import fleets.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendor_type'),
        ('fleets', '0011_rename_pin_code_station_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(default=fleets.models.Charger.code_default, max_length=10, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('connector', models.CharField(max_length=50)),
                ('wattage', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateField()),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Batteries',
            },
        ),
        migrations.RemoveField(
            model_name='vehiclestatuslogs',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclestatuslogs',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'For Deployment'), (1, 'On Ground'), (2, 'Under Maintenance'), (3, 'Under Servicing')]),
        ),
        migrations.DeleteModel(
            name='VehicleStationLogs',
        ),
        migrations.DeleteModel(
            name='VehicleStatusLogs',
        ),
        migrations.AddField(
            model_name='charger',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle'),
        ),
        migrations.AddField(
            model_name='charger',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor'),
        ),
    ]
