# Generated by Django 3.2.13 on 2022-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=10)),
                ("locality", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=10)),
                ("contact_person", models.CharField(max_length=10)),
                ("contact_number", models.BigIntegerField()),
                ("gst", models.CharField(max_length=10)),
                ("account_number", models.BigIntegerField()),
                ("account_name", models.CharField(max_length=10)),
                ("ifsc_code", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
