# Generated by Django 3.2.13 on 2022-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="account_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact_person",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="gst",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="ifsc_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="locality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
