# Generated by Django 3.2.13 on 2022-07-05 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20220623_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='type',
            field=models.IntegerField(choices=[(0, 'Driver'), (1, 'GPS Tracker'), (2, 'Battery')], null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst',
            field=models.CharField(max_length=15),
        ),
    ]
