# Generated by Django 4.1 on 2022-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_alter_vendor_options_alter_vendor_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Driver"),
                    (1, "GPS Tracker"),
                    (2, "Battery"),
                    (3, "Vehicle"),
                    (4, "Charging Station"),
                    (5, "Parking Lot"),
                ],
                null=True,
            ),
        ),
    ]
