# Generated by Django 3.2.13 on 2022-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.IntegerField(choices=[(0, 'Driver'), (1, 'GPS Tracker'), (2, 'Battery'), (3, 'Vehicle'), (4, 'Charging Station'), (5, 'Parking Lot'), (6, 'Finance')], null=True),
        ),
    ]
