# Generated by Django 3.2.13 on 2022-06-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driverlocations",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="drivers.driver"
            ),
        ),
        migrations.AddField(
            model_name="drivercontractlog",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="drivers.drivercontract"
            ),
        ),
        migrations.AddField(
            model_name="drivercontractlog",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="drivers.driver"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vendors.vendor",
            ),
        ),
    ]
