# Generated by Django 3.2.13 on 2022-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="account_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="driver_license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="locality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="street",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="district",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="house",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="landmark",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="loc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="po",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="street",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="subdist",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="vtc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driveraadhardetails",
            name="zip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="drivercontract",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="account_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="driver_license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="locality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="street",
            field=models.CharField(max_length=50),
        ),
    ]
