# Generated by Django 3.2.13 on 2022-07-04 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20220623_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RenameField(
            model_name='driverlocations',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='onboarding',
            old_name='approved_by',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='drivercontractlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='driver',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='drivercontractlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
