# Generated by Django 4.1 on 2022-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_alter_driver_options_alter_onboarding_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="locality",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="driver",
            name="street",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="city",
            field=models.CharField(max_length=50),
        ),
    ]
