# Generated by Django 3.2.13 on 2022-10-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_locality_alter_driver_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='app_version',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drivers.drivercontract'),
        ),
    ]
