# Generated by Django 3.2.13 on 2022-11-22 03:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20221018_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_back',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_front',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_license_back',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_license_front',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='has_driver_license',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='own_house',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_front',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='street',
        ),
        migrations.AddField(
            model_name='driver',
            name='onboarding',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='drivers.onboarding'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='ref_contact_no',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='ref_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='ref_relationship',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
