# Generated by Django 3.2.13 on 2022-11-23 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20221122_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='c_city',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Chennai'), (1, 'Bengaluru')], null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='c_house_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='c_locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='c_pin_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='c_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='c_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='referred_by',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='ref_contact_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='ref_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='ref_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
