# Generated by Django 3.2.13 on 2022-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_auto_20221214_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='permanent_pin_code',
            new_name='permanent_pincode',
        ),
        migrations.RenameField(
            model_name='onboarding',
            old_name='pin_code',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
