# Generated by Django 3.2.13 on 2022-12-23 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_auto_20221216_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='ref_contact_no',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
