# Generated by Django 3.2.13 on 2022-12-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_auto_20221216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='passbook_front',
            field=models.URLField(blank=True, null=True),
        ),
    ]
