# Generated by Django 3.2.13 on 2022-12-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_onboarding_ref_contact_no'),
        ('drivers', '0012_onboarding_passbook_front'),
    ]

    operations = [
    ]
