# Generated by Django 3.2.13 on 2022-07-04 11:34

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220623_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='pricing_config',
            field=models.JSONField(default=clients.models.Client.default_pricing_config),
        ),
        migrations.AlterField(
            model_name='clientstore',
            name='contact_number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
