# Generated by Django 3.2.13 on 2022-11-21 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_rename_pricing_config_client_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Rental'), (1, 'Logistics - Fixed'), (2, 'Logistics - Trip'), (3, 'Logistics - Delivery')], default=1)),
                ('model', models.IntegerField(choices=[(0, 'Pimo'), (1, 'Hero Nyx'), (2, 'Hero Lectro'), (3, 'Treo Zor'), (4, 'Log9'), (5, 'Omega Seiko'), (6, 'Altigreen')])),
                ('price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('client_store', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='client', chained_model_field='client', horizontal=True, null=True, to='clients.ClientStore')),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='ClientContractLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_contract', models.URLField()),
                ('new_contract', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Contract Log',
                'verbose_name_plural': 'Client Contract Logs',
            },
        ),
    ]
