# Generated by Django 3.2.13 on 2022-11-23 11:54

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20221121_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='client_store',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='client', chained_model_field='client', horizontal=True, to='clients.ClientStore'),
        ),
    ]
