# Generated by Django 3.2.13 on 2022-12-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_pricing_client_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='meta',
        ),
    ]
