# Generated by Django 3.2.13 on 2022-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='model',
            field=models.IntegerField(choices=[(0, 'Pimo'), (1, 'Hero Nyx'), (2, 'Hero Lectro'), (3, 'Treo Zor'), (4, 'Log9'), (5, 'Omega Seiki'), (6, 'Altigreen'), (7, 'Exponent')]),
        ),
    ]
