# Generated by Django 3.2.13 on 2022-12-22 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_alter_pricing_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientContractLogs',
            new_name='ClientContractLog',
        ),
    ]
