# Generated by Django 3.2.13 on 2022-11-17 12:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleets', '0008_auto_20221115_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')])),
                ('issue_type', models.IntegerField(choices=[(0, 'Other Issue'), (1, 'Electrical'), (2, 'Mechanical')])),
                ('issue_subtype', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=250)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Medium'), (1, 'High')])),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicing_created_by', to=settings.AUTH_USER_MODEL)),
                ('reportee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicing_reportee', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')])),
                ('new_status', models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')])),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicing')),
            ],
            options={
                'verbose_name': 'Servicing Log',
                'verbose_name_plural': 'Servicing Logs',
            },
        ),
    ]
