# Generated by Django 3.2.13 on 2022-12-22 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0012_auto_20221222_1838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicing',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ServicingLogs',
            new_name='ServiceLog',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Vehicle Service', 'verbose_name_plural': 'Vehicle Services'},
        ),
        migrations.AlterModelOptions(
            name='servicelog',
            options={'verbose_name': 'Vehicle Service Log', 'verbose_name_plural': 'Vehicle Service Logs'},
        ),
    ]
