# Generated by Django 3.2.13 on 2022-06-09 13:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=50, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "holiday",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("slot_start_time", models.TimeField()),
                ("slot_end_time", models.TimeField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("address", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Roster",
                "verbose_name_plural": "Rosters",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("in_time", models.DateTimeField(blank=True, null=True)),
                ("out_time", models.DateTimeField(blank=True, null=True)),
                ("start_ride_time", models.DateTimeField(blank=True, null=True)),
                ("end_ride_time", models.DateTimeField(blank=True, null=True)),
                ("start_km", models.IntegerField(blank=True, null=True)),
                ("end_km", models.IntegerField(blank=True, null=True)),
                ("in_latitude", models.FloatField(blank=True, null=True)),
                ("in_longitude", models.FloatField(blank=True, null=True)),
                ("out_latitude", models.FloatField(blank=True, null=True)),
                ("out_longitude", models.FloatField(blank=True, null=True)),
                ("trip_sheet_photo", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
            },
        ),
    ]
