# Generated by Django 3.2.13 on 2022-06-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="drivers.driver"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="roster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bookings.roster"
            ),
        ),
    ]
