# Generated by Django 3.2.13 on 2022-06-09 13:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleets", "0001_initial"),
        ("clients", "0001_initial"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fleets.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="roster",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="roster",
            name="client_store",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="client",
                chained_model_field="client",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.clientstore",
            ),
        ),
    ]
