# Generated by Django 3.2.13 on 2022-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="address",
            field=models.CharField(max_length=50),
        ),
    ]
