# Generated by Django 3.2.13 on 2022-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_roster_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
