# Generated by Django 4.1 on 2022-09-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_roster_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="end_km_photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_km_photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Ride Started"),
                    (1, "Check In"),
                    (2, "Check Out"),
                    (3, "Ride Completed"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="end_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
