# Generated by Django 4.1 on 2022-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_roster_city_trip_end_km_photo_trip_start_km_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
