# Generated by Django 4.1 on 2022-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_roster_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="address",
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="roster",
            name="city",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="roster",
            name="client_name",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="roster",
            name="lat",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="roster",
            name="long",
            field=models.FloatField(editable=False),
        ),
    ]
