# Generated by Django 3.2.13 on 2022-10-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20221018_1806'),
        ('bookings', '0011_alter_roster_address_alter_roster_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='in_time',
            new_name='checkin_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='out_time',
            new_name='checkout_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='end_ride_time',
            new_name='ended_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_ride_time',
        ),
        migrations.AddField(
            model_name='roster',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Logistics'), (1, 'Rental')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drivers.driver'),
        ),
    ]
