# Generated by Django 3.2.13 on 2022-11-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0008_auto_20221115_2102'),
        ('bookings', '0012_auto_20221018_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='roster',
            name='cost',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rental'), (1, 'Logistics - Fixed'), (2, 'Logistics - Trip'), (3, 'Logistics - Delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='roster',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle'),
        ),
    ]
