# Generated by Django 3.2.13 on 2022-12-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20221121_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='client_name',
        ),
    ]
