# Generated by Django 3.2.13 on 2022-12-16 07:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0010_auto_20221215_1818'),
        ('bookings', '0014_remove_roster_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_km_photo',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_km_photo',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_photo',
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='roster',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleets.vehicle'),
        ),
    ]
