# Generated by Django 3.2.13 on 2022-12-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleets', '0012_auto_20221222_1838'),
        ('drivers', '0013_merge_20221226_1545'),
        ('bookings', '0015_auto_20221216_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Active'), (1, 'Active'), (2, 'Attrition'), (3, 'Service')], default=1),
        ),
        migrations.CreateModel(
            name='RosterVehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In Active'), (1, 'Active'), (2, 'Attrition'), (3, 'Service')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_vehicle', to='fleets.vehicle')),
                ('old_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_vehicle', to='fleets.vehicle')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.roster')),
            ],
            options={
                'verbose_name': 'Roster Vehicle Log',
                'verbose_name_plural': 'Roster Vehicle Logs',
            },
        ),
        migrations.CreateModel(
            name='RosterDriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In Active'), (1, 'Active'), (2, 'Attrition'), (3, 'Service')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_driver', to='drivers.driver')),
                ('old_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_driver', to='drivers.driver')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.roster')),
            ],
            options={
                'verbose_name': 'Roster Driver Log',
                'verbose_name_plural': 'Roster Driver Logs',
            },
        ),
    ]
